---
apiVersion: "v1"
data:
  # The password of the admin client - a client named admin with uaa.admin as an
  # authority.
  uaa-admin-client-secret: {{if ne (typeOf .Values.secrets.UAA_ADMIN_CLIENT_SECRET) "<nil>"}}{{if has (kindOf .Values.secrets.UAA_ADMIN_CLIENT_SECRET) (list "map" "slice")}}{{.Values.secrets.UAA_ADMIN_CLIENT_SECRET | toJson | b64enc | quote}}{{else}}{{.Values.secrets.UAA_ADMIN_CLIENT_SECRET | b64enc | quote}}{{end}}{{else}}{{fail "secrets.UAA_ADMIN_CLIENT_SECRET has not been set"}}{{end}}

  # PEM-encoded CA certificate used to sign the TLS certificate used by all
  # components to secure their communications.
  # This value uses a generated default.
  internal-ca-cert: {{ default "" .Values.secrets.INTERNAL_CA_CERT | b64enc | quote }}

  # PEM-encoded CA key.
  # This value uses a generated default.
  internal-ca-key: {{ default "" .Values.secrets.INTERNAL_CA_KEY | b64enc | quote }}

  # PEM-encoded JWT certificate.
  # This value uses a generated default.
  jwt-signing-cert: {{ default "" .Values.secrets.JWT_SIGNING_CERT | b64enc | quote }}

  # PEM-encoded JWT signing key.
  # This value uses a generated default.
  jwt-signing-key: {{ default "" .Values.secrets.JWT_SIGNING_KEY | b64enc | quote }}

  # Password used for the monit API.
  # This value uses a generated default.
  monit-password: {{ default "" .Values.secrets.MONIT_PASSWORD | b64enc | quote }}

  # The password for the MySQL server admin user.
  # This value uses a generated default.
  mysql-admin-password: {{ default "" .Values.secrets.MYSQL_ADMIN_PASSWORD | b64enc | quote }}

  # The password for the cluster logger health user.
  # This value uses a generated default.
  mysql-cluster-health-password: {{ default "" .Values.secrets.MYSQL_CLUSTER_HEALTH_PASSWORD | b64enc | quote }}

  # The password used to contact the sidecar endpoints via Basic Auth.
  # This value uses a generated default.
  mysql-galera-healthcheck-endpoint-password: {{ default "" .Values.secrets.MYSQL_GALERA_HEALTHCHECK_ENDPOINT_PASSWORD | b64enc | quote }}

  # The password for Basic Auth used to secure the MySQL proxy API.
  # This value uses a generated default.
  mysql-proxy-admin-password: {{ default "" .Values.secrets.MYSQL_PROXY_ADMIN_PASSWORD | b64enc | quote }}

  # PEM-encoded certificate
  # This value uses a generated default.
  saml-serviceprovider-cert: {{ default "" .Values.secrets.SAML_SERVICEPROVIDER_CERT | b64enc | quote }}

  # PEM-encoded key.
  # This value uses a generated default.
  saml-serviceprovider-key: {{ default "" .Values.secrets.SAML_SERVICEPROVIDER_KEY | b64enc | quote }}

  # The server's ssl certificate. The default is a self-signed certificate and
  # should always be replaced for production deployments.
  # This value uses a generated default.
  uaa-server-cert: {{ default "" .Values.secrets.UAA_SERVER_CERT | b64enc | quote }}

  # The server's ssl private key. Only passphrase-less keys are supported.
  # This value uses a generated default.
  uaa-server-key: {{ default "" .Values.secrets.UAA_SERVER_KEY | b64enc | quote }}

  # The password for access to the UAA database.
  # This value uses a generated default.
  uaadb-password: {{ default "" .Values.secrets.UAADB_PASSWORD | b64enc | quote }}

kind: "Secret"
metadata:
  name: "secrets"
  labels:
    skiff-role-name: "secrets"
